name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./gui/src-tauri -> target"

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "npm" # Set this to npm, yarn or pnpm.
          cache-dependency-path: gui/package-lock.json

      - name: Install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: cd gui && npm install # Change this to npm, yarn or pnpm.

      - name: Build the app
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: "Toyhouse Extensions v__VERSION__" # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: |
            Windows:
              - Download `Toyhouse.Extensions_x64_en-US.msi` or `Toyhouse.Extensions_x64-setup.exe`

            Linux:
              - Download `toyhouse-extensions____VERSION____amd64.AppImage`, `toyhouse-extensions_0___VERSION____amd64.deb` or `Toyhouse.Extensions_x64.app.tar.gz`

            [!IMPORTANT]
            Ubuntu 22.04 switched from openssl1.1 to openssl3.0, and this causes Toyhouse Extensions to crash on distros with openssl@v3. To fix this issue, please see [this StackOverflow thread](https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory)

            MacOS:
              - Download `Toyhouse.Extensions____VERSION____x64.dmg`
          releaseDraft: true
          prerelease: false
